Add an option to show or hide navigation menu and include it within the group
croustibat/filament-jobs-monitor pull request #4
Opened 2023-05-31 16:38 UTC by cntabana

2023-05-31 16:44 UTC, cntabana commented
This pull request introduces new functionality that allows users to customize the icon, navigation group, and visibility of the menu through a configuration file. These enhancements provide greater flexibility and customization options for the application.

**Key Changes:**

- Added the ability to change the icon associated with the menu.
- Implemented functionality to modify the navigation group, allowing users to organize menu items according to their preferences.
- Included options to show or hide the menu based on specific requirements.**

These additions enable users to tailor the application's menu to their specific needs, enhancing the user experience and providing a more personalized interface.

Please review this pull request and provide feedback. Your input is greatly appreciated.

2023-06-01 03:19 UTC, mackhankins commented
I don't think groups are controlled by gates.  Would be awesome if I could set that in the config.  I've seen it done before with https://github.com/kenepa/resource-lock/blob/58fec965c9b6dd3b322a259b481bfa763abb9e19/config/resource-lock.php#L68

2023-06-05 21:24 UTC, croustibat commented on config/filament-jobs-monitor.php
> +    ],
I would provide a more readable approach for settings, something like this :

 
```suggestion
    'navigation' => [
        'enabled' => true,
        'group_labels' => 'Settings',
        'icons' => 'heroicon-o-chip',
    ],
```

2023-06-05 21:25 UTC, croustibat commented on src/Resources/QueueMonitorResource.php
> +        return config('filament-jobs-monitor.labels.navigation_group');
According to new config array :

```suggestion
        return config('filament-jobs-monitor.navigation.group_label');
```

2023-06-05 21:25 UTC, croustibat commented on src/Resources/QueueMonitorResource.php
> +        return (bool) config('filament-jobs-monitor.navigation_enabled');
```suggestion
        return (bool) config('filament-jobs-monitor.navigation.enabled');
```

2023-06-05 21:26 UTC, croustibat commented on src/Resources/QueueMonitorResource.php
> +        return config('filament-jobs-monitor.icons.navigation');
```suggestion
        return config('filament-jobs-monitor.navigation.icons');
```

2023-06-05 21:28 UTC, croustibat requested changes
hey thank you for this PR, that's great. i would just propose to write config array differently.

2023-06-13 14:07 UTC, merged